### ISSUE TITLE
HashCode2014.jl is supposed to be a dependency

### ISSUE THREAD

**Issue by gdalle** [davidfang00/Julia_Hashcode2014.jl#3]
Instead you copied all of my code into your package, which is not a good idea. For instance, if I make changes to my code, your copy will not reflect it.

Please remove my source files from your project and add my package as an (unregistered) dependency instead: https://pkgdocs.julialang.org/v1.8/creating-packages/#Adding-dependencies-to-the-project

**Comment by davidfang00** [comment]
Resolved.
